# Paths to CSV files
data:
  supervised_csv: "ID/supervised_training0.05.csv"
  unsupervised_csv: "ID/unsupervised_training0.05.csv"
  val_csv: "ID/val.csv"

# Training hyperparameters
training:
  num_epochs: 30
  batch_size: 4
  num_workers: 4
  lambda_adv: 1.0
  lambda_seg: 100.0
  lambda_pixel: 100.0


# Model save paths
model:
  save_dir: "model_weights/SEL"
  generator: "model_weights/SEL/best_G.pth"
  segmentation: "model_weights/SEL/best_S.pth"
  discriminator: "model_weights/SEL/best_D.pth"

# Optimizer settings
optimizer:
  lr: 0.0002
  betas: [0.5, 0.999]

# Scheduler settings
scheduler:
  step_size: 10
  gamma: 0.1

# Device settings
device:
  use_cuda: true
