device: null

data:
  image_size: 256
  batch_size: 1
  images: dataset/new_test_img
  masks: dataset/new_test_msk

model:
  num_classes: 7

weights:
  generator: model_weights/0.05/0.05joingtraining_aug_noenhance/best_G.pth
  segmenter: model_weights/0.05/0.05joingtraining_aug_noenhance/best_S.pth

outputs:
  prediction_overlay_dir: outputs/prediction_GRN
  ground_truth_overlay_dir: outputs/ground_truth_GRN
